// 入口水平测试的题库：每题标了一个 targetLevel —— 在本次抽到的10题里，
// 如果这题答错了，就把它的 targetLevel 计入候选；最终推荐"候选里最靠前的关卡"作为起点。
// 全部答对 -> 建议直接去 assessment.html 做进阶题目。
// 题库有110+题，每次测试从里面随机抽10题，题目和选项顺序也会打乱（在 quiz-app.js 里处理）。
// 这份题库同时也是"每日复习"里初级部分的题源。

const QUIZ = [
  // ---- print（对应 course 第1关）----
  {
    q: "下面哪一行代码，能在屏幕上显示出文字 \"你好\"？",
    options: ["print(\"你好\")", "show(\"你好\")", "text(\"你好\")", "echo(\"你好\")"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "哪个函数可以把内容显示在屏幕上？",
    options: ["print", "input", "def", "return"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"Hello\") 运行后，屏幕上会出现什么？",
    options: ["Hello", "\"Hello\"", "print(\"Hello\")", "什么都不会出现"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(1, 2, 3) 会输出什么？",
    options: ["1 2 3", "1,2,3", "[1, 2, 3]", "会报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print() 后面括号里的内容，多个用逗号隔开，中间默认会自动加什么？",
    options: ["空格", "换行", "什么都不加", "逗号"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "想要 print() 不自动换行，应该怎么写？",
    options: ["print(x, end=\"\")", "print(x, newline=False)", "noNewline(print(x))", "print.no_newline(x)"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "下面哪一行会报错？",
    options: ["print(5+\"5\")", "print(5+5)", "print(\"5\"+\"5\")", "print(\"5\", 5)"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"a\", \"b\", sep=\"-\") 会输出什么？",
    options: ["a-b", "a,b", "ab", "a b"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "下面哪个不是 print() 的作用？",
    options: ["从用户那里获取输入", "在屏幕上显示内容", "显示多个值", "显示计算结果"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print() 属于 Python 的什么？",
    options: ["内置函数", "关键字", "变量", "数据类型"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"a\" + \"b\") 会输出什么？",
    options: ["ab", "a b", "a+b", "报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print() 括号里什么都不写，直接运行会怎样？",
    options: ["输出一个空行", "报错", "什么都不会发生", "输出None这个词"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"你好\\n世界\") 会输出几行内容？",
    options: ["2行", "1行", "3行", "会报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(1+1, \"equals\", 2) 会输出什么？",
    options: ["2 equals 2", "1+1 equals 2", "2equals2", "报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(True) 会输出什么？",
    options: ["True", "\"True\"", "1", "报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"多个\", \"参数\", \"用空格隔开\") 会输出什么？",
    options: ["多个 参数 用空格隔开", "多个,参数,用空格隔开", "多个参数用空格隔开", "报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(10, 20, sep=\", \") 会输出什么？",
    options: ["10, 20", "10 20", "10,20", "报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"End\", end=\"!\") 会怎样？",
    options: ["输出End!，并且不会自动换行", "输出End!，然后换行", "输出End，然后单独一行!", "报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"It's ok\") 会输出什么？",
    options: ["It's ok", "会报错，因为单引号和双引号混用了", "Its ok", "It\\'s ok"],
    answer: 0,
    targetLevel: 1,
  },

  // ---- 变量（对应第2关）----
  {
    q: "name = \"小明\" 这行代码是在做什么？",
    options: [
      "创建一个叫 name 的变量，把\"小明\"存进去",
      "判断 name 是不是等于\"小明\"",
      "打印\"小明\"这两个字",
      "删除一个叫 name 的变量",
    ],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪一个是合法的变量名？",
    options: ["my_age", "2age", "my age", "class-name"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 5，然后执行 x = x + 1，此时 x 是多少？",
    options: ["6", "5", "x+1", "会报错"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪一行代码会报错？",
    options: ["y = ", "y = 5", "y = \"5\"", "y = \"五\""],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪个变量名是不合法的？",
    options: ["2age", "my_age", "age2", "_age"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 5; y = x; x = 10，此时 y 是多少？",
    options: ["5", "10", "报错", "15"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "Python 的变量在使用前需要先声明类型吗？",
    options: [
      "不需要，赋值时自动确定类型",
      "需要用 int/str 等关键字声明",
      "需要写在文件开头",
      "只有数字类型需要声明",
    ],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "a, b = 1, 2 这行代码是在做什么？",
    options: ["同时给a和b赋值", "报错，一行只能赋一个值", "创建一个元组叫a,b", "比较a和b"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪个是给变量重新赋值？",
    options: ["x = 10 后面又写 x = 20", "x == 20", "del x", "print(x)"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "变量名区分大小写吗（Name 和 name 算不算同一个变量）？",
    options: ["区分，是两个不同的变量", "不区分，是同一个", "只有首字母区分", "取决于操作系统"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "a = 1\nb = 2\na, b = b, a\n执行后 a 和 b 分别是多少？",
    options: ["a=2, b=1", "a=1, b=2（没变）", "报错", "a=2, b=2"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 10\nx = x * 2\nx = x - 5\n最终 x 是多少？",
    options: ["15", "20", "5", "10"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪一个不能用作变量名？",
    options: ["if（Python的关键字）", "name", "age", "score2"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 5\ny = 10\nz = x + y\nprint(z)\n会输出什么？",
    options: ["15", "510", "5 10", "报错"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "name = \"Tom\"\nname = \"Jerry\"\nprint(name)\n会输出什么？",
    options: ["Jerry", "Tom", "TomJerry", "报错，不能给同一个变量赋值两次"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "a, b = 5, 10\nprint(a + b)\n会输出什么？",
    options: ["15", "510", "报错", "5"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "score = 100\nscore = score - 20\nprint(score)\n会输出什么？",
    options: ["80", "100", "-20", "报错"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 5\nx = x + x\nprint(x)\n会输出什么？",
    options: ["10", "5", "55", "报错"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "变量可以在赋值之后改变它存的数据类型吗？比如 x = 5 之后又写 x = \"hello\"？",
    options: ["可以，Python变量的类型可以随时改变", "不可以，类型定了就不能变", "只有数字之间可以互相改变", "会报错"],
    answer: 0,
    targetLevel: 2,
  },

  // ---- 数字运算（对应第3关）----
  {
    q: "两个整数相加，比如 int类型的a加int类型的b，结果一定还是整数吗？",
    options: ["是的，两个int相加结果还是int", "不一定，可能变成字符串", "会变成浮点数", "取决于数字大小"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "一个整数和一个浮点数（小数）相加，结果是什么类型？",
    options: ["浮点数（只要有一方是小数，结果就是小数）", "整数", "字符串", "报错，不能相加"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "Python里，数字主要分为整数（int）和浮点数（float）这两大类，对吗？",
    options: ["对，这是最基本的两种数字类型", "不对，Python只有一种数字类型", "不对，还有专门的\"运算数\"类型", "对，但两者不能混合运算"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "a = 6，b = 3，表达式 a - b 在做什么？",
    options: ["用a的值减去b的值", "把a和b拼在一起", "判断a是否等于b", "把b的值改成a"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "同一个数字，写成 6 和写成 6.0，在Python里是完全一样的类型吗？",
    options: ["不一样，6是整数（int），6.0是浮点数（float）", "完全一样，只是写法不同", "6.0不合法，Python不能这样写", "取决于变量名"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "为什么 Python 3 里，两个整数相除（用 /）结果永远带小数点（比如变成4.0而不是4）？",
    options: ["因为 / 这个除法运算符的结果类型永远是浮点数，不管能不能整除", "这是一个bug", "只有偶数相除才会这样", "取决于Python的版本设置"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "带负号的数字，比如 -5，在Python里是合法的写法吗？",
    options: ["是合法的，负号是数字的一部分", "不合法，负数需要写成0-5", "只有浮点数能带负号", "需要额外导入模块才能用负数"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "多个数字连续相乘，比如 a * b * c，Python会怎么计算？",
    options: ["从左到右依次计算（先算a*b，再乘c）", "从右到左计算", "同时计算三个数", "报错，一个表达式最多两个数相乘"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "8 / 2 的结果类型是？",
    options: ["浮点数（4.0）", "整数（4）", "字符串", "报错"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "下面哪个说法是对的？",
    options: [
      "* 和 / 的优先级比 + 和 - 高，会先算",
      "四则运算永远从左往右算，不看符号优先级",
      "括号在Python里不能改变运算顺序",
      "+ 的优先级比 * 高",
    ],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "** 运算符在Python里表示什么运算？",
    options: ["乘方（幂运算），比如2**3表示2的3次方", "乘法", "整除", "取余"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "% 运算符求的是两个数相除之后的什么？",
    options: ["余数", "商", "商加余数", "两数之差"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "// 和 / 这两个除法运算符，最主要的区别是？",
    options: ["// 的结果只保留整数部分（向下取整），/ 会保留小数部分", "两者完全一样", "// 更快，结果和/相同", "/ 只能用在整数上"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "Python计算表达式的时候，运算符之间有优先级顺序吗？",
    options: ["有，比如乘除会比加减先算，跟数学课学的规则一致", "没有，永远从左往右依次计算", "只有加减法有优先级", "取决于变量名"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "圆括号 () 在Python表达式里的作用是？",
    options: ["改变运算的先后顺序，括号里的部分永远最先算", "只是用来分隔代码，不影响运算顺序", "表示这是一个函数调用，不能用来分组运算", "Python表达式里不能使用圆括号"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "如果一个算式同时有加减乘除，Python是严格从左到右依次算，还是按照优先级算？",
    options: ["按照优先级算（先乘除后加减），不是单纯从左到右", "严格从左到右，不看运算符种类", "从右到左算", "由用户手动指定顺序"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "用 / 除法和用 // 除法，结果的数据类型分别是什么？",
    options: ["/ 的结果永远是浮点数（小数），// 的结果是整数", "两者结果类型完全一样", "/ 是整数，// 是浮点数（和实际相反）", "取决于参与运算的数字大小"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "想求一个数的绝对值（去掉负号，比如把-5变成5），用哪个函数？",
    options: ["abs()", "positive()", "unsign()", "neg()"],
    answer: 0,
    targetLevel: 3,
  },

  // ---- f-string（对应第4关）----
  {
    q: "name = \"小明\"，下面哪一行能打印出\"你好，小明\"？",
    options: [
      "print(f\"你好，{name}\")",
      "print(\"你好，name\")",
      "print(你好，name)",
      "print{\"你好，\" name}",
    ],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "下面哪个是正确的 f-string 写法？",
    options: ["f\"你好{name}\"", "\"f你好{name}\"", "f\"你好(name)\"", "print f\"你好{name}\""],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "name = \"小红\"，print(f\"{name}你好\") 会输出什么？",
    options: ["小红你好", "{name}你好", "name你好", "会报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "想在一句话里同时显示姓名和年龄两个变量的值，用什么方法最合适？",
    options: ["f-string", "分开print很多次再手动拼起来", "把变量名直接写进普通字符串里", "没办法做到"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "x = 5; print(f\"结果是{x*2}\") 会输出什么？",
    options: ["结果是10", "结果是{x*2}", "结果是x*2", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "f-string 里的花括号 {} 可以放什么？",
    options: ["变量或表达式", "只能放变量", "只能放数字", "什么都不能放"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "下面哪个是正确的 f-string？",
    options: ["f\"值是{x}\"", "\"f值是{x}\"", "f值是{x}", "f\"值是\"{x}"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "不用 f-string，还有其他方法能拼接字符串和变量吗？",
    options: [
      "有，比如用 + 号拼接（需要先转成字符串）",
      "没有，只能用 f-string",
      "只能用 print 多次",
      "只有C语言能做到",
    ],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "name = \"Tom\"; print(f\"{name}\") 和 print(name) 结果一样吗？",
    options: ["一样", "不一样", "会报错", "取决于Python版本"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "f-string 是 Python 哪个版本开始支持的？",
    options: ["3.6+", "2.7", "1.0", "所有版本都支持"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "age = 13，print(f\"我{age}岁了\") 会输出什么？",
    options: ["我13岁了", "我age岁了", "我{age}岁了", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "x = 3; y = 4，print(f\"{x}+{y}={x+y}\") 会输出什么？",
    options: ["3+4=7", "x+y=x+y", "{x}+{y}={x+y}", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "想在 f-string 里显示真正的花括号 {}（而不是当成变量占位符），应该怎么写？",
    options: ["用两个花括号 {{ }}", "用反斜杠 \\{ \\}", "没办法显示花括号", "用中括号 [ ] 代替"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "price = 9.9\nprint(f\"价格是{price}元\")\n会输出什么？",
    options: ["价格是9.9元", "价格是price元", "价格是{price}元", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "a = 2; b = 3\nprint(f\"{a}*{b}={a*b}\")\n会输出什么？",
    options: ["2*3=6", "a*b=a*b", "{a}*{b}={a*b}", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "name = \"Amy\"\nprint(f\"Hi {name}!\")\n会输出什么？",
    options: ["Hi Amy!", "Hi name!", "Hi {name}!", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "f\"{1+1}\" 这个f-string本身的结果，是字符串\"2\"还是数字2？",
    options: ["字符串\"2\"，f-string最终结果永远是字符串", "数字2", "取决于表达式类型", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "name = \"Lily\"; age = 10\nprint(f\"{name}是{age}岁\")\n会输出什么？",
    options: ["Lily是10岁", "name是age岁", "{name}是{age}岁", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "f-string 前面的字母 f 大小写重要吗（f\"...\" 和 F\"...\"）？",
    options: ["不重要，小写f和大写F都可以", "重要，只能用小写f", "重要，只能用大写F", "两种写法意思完全不同"],
    answer: 0,
    targetLevel: 4,
  },

  // ---- input（对应第5关）----
  {
    q: "input() 函数的作用是？",
    options: ["让程序暂停，等待用户输入内容", "打印内容", "做数学运算", "创建一个函数"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "name = input(\"你叫什么？\")，用户输入的内容会被存到哪里？",
    options: ["变量 name 里", "直接打印出来，不会保存", "丢失掉", "存到一个列表里"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input() 返回的数据类型是？",
    options: ["字符串（文字）", "整数", "小数", "列表"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "想把 input() 的结果当成数字来做加法，应该怎么做？",
    options: ["用 int() 转换一下", "直接加就行", "input() 自动就是数字", "做不到"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input() 会暂停程序，直到用户做什么？",
    options: ["输入内容并按回车", "关闭浏览器", "点击按钮", "等待5秒"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "想要把 input() 的结果变成整数进行计算，应该怎么做？",
    options: ["int(input())", "input().toInt()", "(int)input()", "input() 自动是整数"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input(\"提示语\") 里的提示语会显示在哪里？",
    options: ["输入前，提示用户要输入什么", "输入后", "不会显示", "只在网页版显示"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "下面哪个说法正确？",
    options: [
      "input() 的返回值永远是字符串类型",
      "input() 的返回值永远是数字",
      "input() 自动判断类型",
      "input() 不能加提示文字",
    ],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "如果用户直接按回车不输入任何内容，input() 会返回什么？",
    options: ["空字符串 \"\"", "None", "报错", "0"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input() 函数是 Python 的什么？",
    options: ["内置函数", "关键字", "数据类型", "运算符"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "age = input(\"你几岁？\")，用户输入13后按回车，age 的值和类型是？",
    options: ["字符串 \"13\"，不是数字13", "数字13", "None", "报错"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "想让程序先问名字，再问年龄，需要调用几次 input()？",
    options: ["两次，分开写两行", "一次就够，input()能同时问两个问题", "不需要调用input()", "三次"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "n = int(input())，如果用户输入的不是数字（比如输入\"abc\"），会发生什么？",
    options: ["报错（无法把\"abc\"转换成整数）", "n会变成0", "n会变成None", "程序会自动忽略这次输入"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "num1 = int(input())\nnum2 = int(input())\nprint(num1 + num2)\n这段代码在做什么？",
    options: ["读入两个数字并把它们相加打印出来", "只读入一个数字", "把两次输入拼接成字符串", "报错"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input() 里的提示语可以不写吗？比如直接写 input()？",
    options: ["可以，提示语是可选的", "不可以，必须写提示语", "不写会报错", "不写的话程序不会暂停等待输入"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "name = input(\"你叫什么？\").strip() 里的 .strip() 起什么作用？",
    options: ["去掉输入内容前后多余的空格", "把输入内容变成大写", "把输入内容反过来", "报错"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "如果想连续问用户三个不同的问题，各自存到不同变量里，需要写几个 input()？",
    options: ["三个", "一个就够", "两个", "不需要input()"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "float(input()) 和 int(input()) 的区别是？",
    options: ["float()能转换成小数，int()只能转换成整数", "两者完全一样", "float()更快", "int()能处理小数，float()不能"],
    answer: 0,
    targetLevel: 5,
  },

  // ---- if 判断（对应第6关）----
  {
    q: "score = 55，下面这段代码会打印什么？\nif score >= 60:\n    print(\"及格\")\nelse:\n    print(\"不及格\")",
    options: ["不及格", "及格", "会报错", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if 后面的条件写完，必须要有什么符号？",
    options: ["冒号 :", "分号 ;", "逗号 ,", "感叹号 !"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "下面哪个说法是对的？",
    options: ["else 不能单独出现，必须配合 if 使用", "else 可以单独使用", "if 不需要缩进", "if 只能用一次"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "x = 10\nif x > 5:\n    print(\"A\")\nelse:\n    print(\"B\")\n会输出什么？",
    options: ["A", "B", "AB", "会报错"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if 后面的条件表达式，结果需要是什么？",
    options: ["能判断真假的值", "必须是数字", "必须是字符串", "必须是True或False这两个字面量"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "else 可以脱离 if 单独使用吗？",
    options: ["不可以，必须配合if", "可以，随时能用", "只有在函数里才能单独用", "取决于Python版本"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "一个 if 语句最多能跟几个 elif？",
    options: ["没有限制，可以写很多个", "最多1个", "最多3个", "不能有elif"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if x > 5:\n    print(\"a\")\nprint(\"b\")\n当 x=10 时会打印什么？",
    options: ["a和b都打印", "只打印a", "只打印b", "都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "下面哪个写法会导致语法错误？",
    options: ["if x > 5 print(\"a\")（缺少冒号）", "if x > 5: print(\"a\")", "if (x > 5): print(\"a\")", "if x>5:\n    print(\"a\")"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "not、and、or 是什么？",
    options: ["逻辑运算符，用来组合多个条件", "变量名", "函数名", "数据类型"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "x = 5\nif x > 10:\n    print(\"大\")\nelif x > 3:\n    print(\"中\")\nelse:\n    print(\"小\")\n会打印什么？",
    options: ["中", "大", "小", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if 5 > 3 and 2 > 4:\n    print(\"yes\")\nelse:\n    print(\"no\")\n会打印什么？",
    options: ["no", "yes", "报错", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "一个数既要大于0又要小于100才算合法，应该用 and 还是 or 连接这两个条件？",
    options: ["and（两个条件都要满足）", "or（满足一个就行）", "两者效果一样", "都不对，需要用not"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "age = 20\nif age >= 18:\n    print(\"成年\")\nelse:\n    print(\"未成年\")\n会打印什么？",
    options: ["成年", "未成年", "都打印", "报错"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "x = 0\nif x:\n    print(\"真\")\nelse:\n    print(\"假\")\n会打印什么？",
    options: ["假（数字0在if里被当成False）", "真", "报错", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "score = 59\nif score >= 60:\n    print(\"及格\")\nelif score >= 50:\n    print(\"接近及格\")\nelse:\n    print(\"不及格\")\n会打印什么？",
    options: ["接近及格", "及格", "不及格", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "判断一个数n是否在1到100之间（包含1和100），条件应该怎么写？",
    options: ["n >= 1 and n <= 100", "n >= 1 or n <= 100", "n = 1 and n = 100", "n > 1 and n < 100（不含边界）"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "在Python里，其他语言的 \"else if\" 应该写成什么？",
    options: ["elif", "else if", "elseif", "else_if"],
    answer: 0,
    targetLevel: 6,
  },

  // ---- for 循环（对应第7关）----
  {
    q: "range(1, 4) 依次会产生哪些数字？",
    options: ["1, 2, 3", "1, 2, 3, 4", "0, 1, 2, 3", "1, 4"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(3): print(i) 会打印几行？",
    options: ["3行", "4行", "2行", "0行"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for 循环主要用来做什么？",
    options: ["重复执行一段代码", "判断条件", "存储数据", "定义函数"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "range(5) 里的第一个数字是？",
    options: ["0", "1", "5", "-1"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(3, 8): 会产生哪些数字？",
    options: ["3,4,5,6,7", "3,4,5,6,7,8", "4,5,6,7,8", "3到8所有数（含小数）"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "range(0, 10, 2) 会产生哪些数字？",
    options: ["0,2,4,6,8", "0,1,2...10", "2,4,6,8,10", "0到10所有偶数含10"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for 循环里的变量名（比如 for i in ... 里的 i）能随便起吗？",
    options: ["能，符合变量命名规则就行", "不能，必须叫i", "只能是单个字母", "必须提前声明"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for item in [1,2,3]: 这种写法叫什么？",
    options: ["遍历列表", "创建列表", "删除列表", "排序列表"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for 循环执行的次数由什么决定？",
    options: ["range()或者被遍历对象的长度", "电脑性能", "随机决定", "必须手动写死次数"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "下面哪个循环会打印5次？",
    options: ["for i in range(5)", "for i in range(1,5)", "for i in range(0,5,2)", "for i in range(4)"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "total = 0\nfor i in range(1, 5):\n    total += i\nprint(total)\n会输出什么？",
    options: ["10", "9", "15", "4"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(3):\n    print(\"Hi\")\n会打印几次\"Hi\"？",
    options: ["3次", "2次", "4次", "0次"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "想遍历列表 fruits 里的每一个元素并打印出来，应该怎么写？",
    options: ["for f in fruits:\n    print(f)", "for fruits in f:\n    print(f)", "while fruits: print(f)", "print(fruits[all])"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(2, 10, 3): 会产生哪些数字？",
    options: ["2, 5, 8", "2, 3, 4...10", "3, 6, 9", "2, 10"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "total = 1\nfor i in range(1, 5):\n    total *= i\nprint(total)\n会输出什么？",
    options: ["24", "10", "4", "120"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(5):\n    if i == 3:\n        break\n    print(i)\n会打印哪些数字？",
    options: ["0, 1, 2", "0, 1, 2, 3", "0, 1, 2, 3, 4", "3"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(5):\n    if i == 2:\n        continue\n    print(i)\n会打印哪些数字？",
    options: ["0, 1, 3, 4", "0, 1, 2, 3, 4", "2", "0, 1"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(1, 11): 这个循环一共会执行几次？",
    options: ["10次", "11次", "9次", "1次"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "想倒着数从5到1（5,4,3,2,1），range() 应该怎么写？",
    options: ["range(5, 0, -1)", "range(1, 5)", "range(5, 1)", "range(0, 5, -1)"],
    answer: 0,
    targetLevel: 7,
  },

  // ---- while 循环（对应第8关）----
  {
    q: "while 循环会在什么情况下停止？",
    options: ["条件变成 False", "永远不会停止", "执行一次后自动停止", "遇到 print 就停止"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "下面哪段代码会变成\"死循环\"（永远停不下来）？",
    options: [
      "count = 1\nwhile count < 5:\n    print(count)",
      "count = 1\nwhile count < 5:\n    print(count)\n    count = count + 1",
      "for i in range(5):\n    print(i)",
      "print(\"hello\")",
    ],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while 和 for 循环最主要的区别是？",
    options: [
      "while更适合\"不确定要循环几次，只看条件满不满足\"的情况",
      "while只能循环1次",
      "while不能配合if使用",
      "两者完全没有区别",
    ],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "count = 0\nwhile count < 3:\n    count = count + 1\n执行结束后 count 最终是多少？",
    options: ["3", "2", "0", "死循环，不会结束"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while True: 会发生什么？",
    options: ["无限循环，除非里面有break等方式跳出", "立刻结束", "报错", "只执行一次"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while循环和for循环，哪个更适合\"不知道要循环几次，只看条件\"的场景？",
    options: ["while", "for", "两者一样", "都不适合"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "break 关键字在循环里的作用是？",
    options: ["立刻跳出当前循环", "跳过这一次循环", "结束整个程序", "重新开始循环"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "continue 关键字在循环里的作用是？",
    options: ["跳过这一次循环剩下的代码，继续下一次循环", "立刻跳出循环", "结束程序", "什么都不做"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while循环最容易犯的错误是什么？",
    options: ["忘记让条件变化，导致死循环", "变量名起错", "忘记print", "用了中文标点"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "下面哪段代码会立刻结束循环，不打印任何东西？",
    options: ["while False: print(\"a\")", "while True: print(\"a\")", "while 1: print(\"a\")", "for i in range(1): print(\"a\")"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "n = 5\nwhile n > 0:\n    n -= 1\nprint(n)\n最终会打印什么？",
    options: ["0", "5", "1", "死循环"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "i = 0\nwhile i < 3:\n    print(i)\n    i += 1\n会依次打印哪些数字？",
    options: ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "只打印0"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "写 while 循环时，循环体里通常需要做什么，才能避免死循环？",
    options: ["让循环条件相关的变量发生变化", "多写几个print", "把条件写成True", "什么都不用做"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "n = 1\nwhile n <= 5:\n    print(n)\n    n += 1\n一共打印了几行？",
    options: ["5行", "4行", "6行", "死循环"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "x = 10\nwhile x != 0:\n    x -= 2\nprint(x)\n最终会打印什么？",
    options: ["0", "10", "-2", "死循环"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "count = 0\nwhile count < 3:\n    count += 1\n    print(\"循环中\")\nprint(\"结束\")\n一共打印了几次\"循环中\"？",
    options: ["3次", "2次", "4次", "0次"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while 循环的条件里，可以用 and / or 组合多个判断吗？",
    options: ["可以，比如 while x > 0 and y > 0:", "不可以，while只能跟一个条件", "只有if能用and/or", "会报错"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "n = 5\nwhile n > 0:\n    if n == 3:\n        break\n    print(n)\n    n -= 1\n会打印哪些数字？",
    options: ["5, 4", "5, 4, 3, 2, 1", "3", "5, 4, 3"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while循环里的break和continue，主要区别是？",
    options: ["break直接跳出整个循环，continue只跳过这一次剩下的代码", "两者效果完全一样", "break只能用在for里", "continue会结束整个程序"],
    answer: 0,
    targetLevel: 8,
  },

  // ---- 列表（对应第9关）----
  {
    q: "fruits = [\"苹果\", \"香蕉\", \"橙子\"]，fruits[1] 是？",
    options: ["香蕉", "苹果", "橙子", "会报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "列表用什么符号来定义？",
    options: ["方括号 []", "花括号 {}", "圆括号 ()", "尖括号 <>"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [10, 20, 30]，nums[0] 是？",
    options: ["10", "20", "30", "会报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "想把一个新元素加到列表末尾，用哪个方法？",
    options: [".append()", ".add()", ".insert(0)", ".push()"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "len([1,2,3,4]) 的结果是？",
    options: ["4", "3", "[1,2,3,4]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1,2,3]; nums.append(4) 之后 nums 是？",
    options: ["[1,2,3,4]", "[4,1,2,3]", "[1,2,3]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "列表可以装不同类型的数据吗（比如同时装数字和文字）？",
    options: ["可以", "不可以，必须都是同一类型", "只有字符串列表可以", "取决于Python版本"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums[1:3] 这种写法叫什么？",
    options: ["切片，取出下标1到2（不含3）的部分", "取第1到第3个", "报错", "删除操作"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "空列表怎么创建？",
    options: ["[]", "{}", "()", "null"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "列表是有序的吗（元素的顺序会保留吗）？",
    options: ["是的，顺序和添加时一致", "不是，会自动排序", "不是，顺序随机", "取决于元素类型"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1, 2, 3]，nums[-1] 的结果是？",
    options: ["3", "1", "报错", "None"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1, 2, 3]\nnums.remove(2)\nprint(nums)\n会输出什么？",
    options: ["[1, 3]", "[1, 2, 3]", "[2]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [5, 3, 8, 1]\nnums.sort()\nprint(nums)\n会输出什么？",
    options: ["[1, 3, 5, 8]", "[5, 3, 8, 1]", "[8, 5, 3, 1]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1, 2, 3]\nnums.insert(0, 0)\nprint(nums)\n会输出什么？",
    options: ["[0, 1, 2, 3]", "[1, 2, 3, 0]", "[0, 2, 3]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1, 2, 3, 4, 5]\nprint(nums[1:4])\n会输出什么？",
    options: ["[2, 3, 4]", "[1, 2, 3, 4]", "[2, 3, 4, 5]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "a = [1, 2]\nb = [3, 4]\nprint(a + b)\n会输出什么？",
    options: ["[1, 2, 3, 4]", "[4, 6]", "报错，列表不能相加", "[1, 2] [3, 4]"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [3, 1, 2]\nprint(sorted(nums))\nprint(nums)\n第二行打印的nums是？",
    options: ["[3, 1, 2]（sorted()不会修改原列表）", "[1, 2, 3]（原列表也被排序了）", "报错", "[]"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "\"苹果\" in [\"苹果\", \"香蕉\"] 的结果是？",
    options: ["True", "False", "报错", "\"苹果\""],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1, 2, 3]\nnums.pop()\nprint(nums)\n会输出什么？",
    options: ["[1, 2]", "[2, 3]", "[1, 2, 3]", "报错"],
    answer: 0,
    targetLevel: 9,
  },

  // ---- 字典（对应第10关）----
  {
    q: "字典用什么符号来定义？",
    options: ["花括号 {}", "方括号 []", "圆括号 ()", "双引号 \"\""],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "person = {\"name\": \"小明\", \"age\": 13}，怎么取出年龄？",
    options: ["person[\"age\"]", "person[age]", "person.age", "person(age)"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "字典和列表最大的不同是？",
    options: [
      "字典用\"键\"取值，列表用\"位置(下标)\"取值",
      "字典不能存文字",
      "列表不能存数字",
      "两者没有区别",
    ],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "{\"a\": 1, \"b\": 2} 这个字典里有几对键值？",
    options: ["2", "1", "3", "0"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "字典的键（key）可以重复吗？",
    options: ["不可以，重复会覆盖之前的值", "可以，都会保留", "可以，但会报警告", "取决于值的类型"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "怎么判断一个键在不在字典里？",
    options: ["\"键\" in 字典", "字典.has(\"键\")", "字典.contains(\"键\")", "字典[\"键\"] == True"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "person = {\"name\": \"小明\"}; person[\"age\"] = 13 之后会发生什么？",
    options: ["给字典新增一个age键值对", "报错，因为age键不存在", "什么都不会发生", "覆盖name的值"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "字典的键一般用什么类型？",
    options: ["字符串或数字这类不可变类型", "只能是字符串", "只能是数字", "可以是列表"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "空字典怎么创建？",
    options: ["{}", "[]", "()", "dict[]"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "person.get(\"age\", 0) 这行代码的意思是？",
    options: ["取age的值，如果不存在返回默认值0", "把age设成0", "删除age这个键", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d = {\"a\": 1, \"b\": 2}\ndel d[\"a\"]\nprint(d)\n会输出什么？",
    options: ["{'b': 2}", "{'a': 1}", "{}", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d = {}\nd[\"x\"] = 10\nprint(d[\"x\"])\n会输出什么？",
    options: ["10", "\"x\"", "None", "报错，d是空字典不能赋值"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "想遍历字典 d 的所有键，应该怎么写？",
    options: ["for key in d:", "for key in d.values():", "for d in key:", "while d:"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d = {\"a\": 1, \"b\": 2}\nprint(\"a\" in d)\n会输出什么？",
    options: ["True", "False", "1", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d = {\"x\": 1}\nd[\"x\"] = d[\"x\"] + 1\nprint(d)\n会输出什么？",
    options: ["{'x': 2}", "{'x': 1}", "{'x': 11}", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d1 = {\"a\": 1}\nd2 = {\"b\": 2}\nd1.update(d2)\nprint(d1)\n会输出什么？",
    options: ["{'a': 1, 'b': 2}", "{'b': 2}", "{'a': 1}", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "person = {\"name\": \"Tom\", \"age\": 20}\nprint(len(person))\n会输出什么？",
    options: ["2（两对键值）", "3", "20", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d = {\"a\": 1, \"b\": 2, \"c\": 3}\nfor k in d:\n    print(k)\n一共会打印几行？",
    options: ["3行", "1行", "6行", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "字典的键可以用数字吗，比如 {1: \"one\", 2: \"two\"}？",
    options: ["可以，键不一定是字符串", "不可以，键只能是字符串", "只有0可以当键", "会报错"],
    answer: 0,
    targetLevel: 10,
  },

  // ---- 函数（对应第11关）----
  {
    q: "def 关键字在 Python 里是用来做什么的？",
    options: ["创建一个函数", "创建一个变量", "写一个判断条件", "写一个循环"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "函数最大的好处是？",
    options: ["避免重复写同样的代码", "让代码运行变快", "让代码变得更长", "没有好处"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "下面哪一个是正确定义函数的写法？",
    options: ["def greet(name):", "function greet(name):", "def greet(name)", "greet(name):"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "调用一个已经定义好的函数 greet，应该怎么写？",
    options: ["greet(\"小明\")", "def greet(\"小明\")", "call greet(\"小明\")", "greet[\"小明\"]"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "函数如果没有 return 语句，调用它会返回什么？",
    options: ["None", "0", "空字符串", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def greet(name=\"小明\"): 这种写法叫什么？",
    options: ["默认参数", "必填参数", "返回值", "局部变量"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "函数内部创建的变量，函数外面能访问吗？",
    options: ["不能，这是局部变量", "能，所有变量都是全局的", "取决于变量名", "只有数字类型不能"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "调用函数和定义函数，哪个要写在前面？",
    options: ["必须先定义，再调用", "必须先调用，再定义", "顺序不影响", "只要在同一个文件就行"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "return 和 print 在函数里的区别是？",
    options: [
      "return把值返回给调用者可以继续用，print只是显示在屏幕上",
      "没有区别",
      "return更快",
      "print不能在函数里用",
    ],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def add(a, b): return a + b，调用 add(3, 5) 的结果是？",
    options: ["8", "35", "报错", "None"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def square(x):\n    return x * x\nprint(square(4))\n会输出什么？",
    options: ["16", "8", "4", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def greet(name):\n    print(f\"你好，{name}\")\ngreet(\"小明\")\n会输出什么？",
    options: ["你好，小明", "你好，name", "greet(小明)", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "一个函数可以同时接收多个参数吗？",
    options: ["可以，用逗号隔开多个参数", "不可以，只能有一个参数", "最多只能有两个参数", "取决于返回值类型"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def add(a, b):\n    return a + b\nresult = add(2, 3) + add(4, 5)\nprint(result)\n会输出什么？",
    options: ["14", "9", "5", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def greet():\n    print(\"Hi\")\ngreet()\ngreet()\n会打印几次\"Hi\"？",
    options: ["2次", "1次", "0次", "报错，函数不能调用两次"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def double(x):\n    x = x * 2\n    return x\nprint(double(5))\n会输出什么？",
    options: ["10", "5", "None", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "一个函数内部可以调用另一个已经定义好的函数吗？",
    options: ["可以", "不可以，函数之间互相独立", "只有主函数能调用其他函数", "会报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def max_of_two(a, b):\n    if a > b:\n        return a\n    return b\nmax_of_two(3, 7) 的结果是？",
    options: ["7", "3", "10", "None"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "写函数时，参数名和调用时传进去的变量名必须完全一样吗？",
    options: ["不需要一样，函数内部用自己的参数名", "必须一样，否则报错", "只有第一个参数需要一样", "取决于参数类型"],
    answer: 0,
    targetLevel: 11,
  },
];
