// 入口水平测试的题库：每题标了一个 targetLevel —— 在本次抽到的10题里，
// 如果这题答错了，就把它的 targetLevel 计入候选；最终推荐"候选里最靠前的关卡"作为起点。
// 全部答对 -> 建议直接去 assessment.html 做进阶题目。
// 题库有110+题，每次测试从里面随机抽10题，题目和选项顺序也会打乱（在 quiz-app.js 里处理）。
// 这份题库同时也是"每日复习"里初级部分的题源。

const QUIZ = [
  // ---- print（对应 course 第1关）----
  {
    q: "下面哪一行代码，能在屏幕上显示出文字 \"你好\"？",
    options: ["print(\"你好\")", "show(\"你好\")", "text(\"你好\")", "echo(\"你好\")"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "哪个函数可以把内容显示在屏幕上？",
    options: ["print", "input", "def", "return"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"Hello\") 运行后，屏幕上会出现什么？",
    options: ["Hello", "\"Hello\"", "print(\"Hello\")", "什么都不会出现"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(1, 2, 3) 会输出什么？",
    options: ["1 2 3", "1,2,3", "[1, 2, 3]", "会报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print() 后面括号里的内容，多个用逗号隔开，中间默认会自动加什么？",
    options: ["空格", "换行", "什么都不加", "逗号"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "想要 print() 不自动换行，应该怎么写？",
    options: ["print(x, end=\"\")", "print(x, newline=False)", "noNewline(print(x))", "print.no_newline(x)"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "下面哪一行会报错？",
    options: ["print(5+\"5\")", "print(5+5)", "print(\"5\"+\"5\")", "print(\"5\", 5)"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"a\", \"b\", sep=\"-\") 会输出什么？",
    options: ["a-b", "a,b", "ab", "a b"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "下面哪个不是 print() 的作用？",
    options: ["从用户那里获取输入", "在屏幕上显示内容", "显示多个值", "显示计算结果"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print() 属于 Python 的什么？",
    options: ["内置函数", "关键字", "变量", "数据类型"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"a\" + \"b\") 会输出什么？",
    options: ["ab", "a b", "a+b", "报错"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print() 括号里什么都不写，直接运行会怎样？",
    options: ["输出一个空行", "报错", "什么都不会发生", "输出None这个词"],
    answer: 0,
    targetLevel: 1,
  },
  {
    q: "print(\"你好\\n世界\") 会输出几行内容？",
    options: ["2行", "1行", "3行", "会报错"],
    answer: 0,
    targetLevel: 1,
  },

  // ---- 变量（对应第2关）----
  {
    q: "name = \"小明\" 这行代码是在做什么？",
    options: [
      "创建一个叫 name 的变量，把\"小明\"存进去",
      "判断 name 是不是等于\"小明\"",
      "打印\"小明\"这两个字",
      "删除一个叫 name 的变量",
    ],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪一个是合法的变量名？",
    options: ["my_age", "2age", "my age", "class-name"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 5，然后执行 x = x + 1，此时 x 是多少？",
    options: ["6", "5", "x+1", "会报错"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪一行代码会报错？",
    options: ["y = ", "y = 5", "y = \"5\"", "y = \"五\""],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪个变量名是不合法的？",
    options: ["2age", "my_age", "age2", "_age"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 5; y = x; x = 10，此时 y 是多少？",
    options: ["5", "10", "报错", "15"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "Python 的变量在使用前需要先声明类型吗？",
    options: [
      "不需要，赋值时自动确定类型",
      "需要用 int/str 等关键字声明",
      "需要写在文件开头",
      "只有数字类型需要声明",
    ],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "a, b = 1, 2 这行代码是在做什么？",
    options: ["同时给a和b赋值", "报错，一行只能赋一个值", "创建一个元组叫a,b", "比较a和b"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪个是给变量重新赋值？",
    options: ["x = 10 后面又写 x = 20", "x == 20", "del x", "print(x)"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "变量名区分大小写吗（Name 和 name 算不算同一个变量）？",
    options: ["区分，是两个不同的变量", "不区分，是同一个", "只有首字母区分", "取决于操作系统"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "a = 1\nb = 2\na, b = b, a\n执行后 a 和 b 分别是多少？",
    options: ["a=2, b=1", "a=1, b=2（没变）", "报错", "a=2, b=2"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "x = 10\nx = x * 2\nx = x - 5\n最终 x 是多少？",
    options: ["15", "20", "5", "10"],
    answer: 0,
    targetLevel: 2,
  },
  {
    q: "下面哪一个不能用作变量名？",
    options: ["if（Python的关键字）", "name", "age", "score2"],
    answer: 0,
    targetLevel: 2,
  },

  // ---- 数字运算（对应第3关）----
  {
    q: "在 Python 里，10 // 3 的结果是？",
    options: ["3", "3.33", "1", "会报错"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "4 + 5 * 2 的结果是？",
    options: ["14", "18", "9", "20"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "10 / 4 的结果是？",
    options: ["2.5", "2", "3", "2.0"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "a = 6，b = 3，a - b 的结果是？",
    options: ["3", "9", "2", "18"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "2 + 3 * 4 的结果是？",
    options: ["14", "20", "24", "9"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "(2 + 3) * 4 的结果是？",
    options: ["20", "14", "9", "24"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "5 - 2 - 1 的结果是？",
    options: ["2", "4", "-2", "6"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "3 * 3 * 3 的结果是？",
    options: ["27", "9", "18", "6"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "8 / 2 的结果类型是？",
    options: ["浮点数（4.0）", "整数（4）", "字符串", "报错"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "下面哪个说法是对的？",
    options: [
      "* 和 / 的优先级比 + 和 - 高，会先算",
      "四则运算永远从左往右算，不看符号优先级",
      "括号在Python里不能改变运算顺序",
      "+ 的优先级比 * 高",
    ],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "2 ** 4 的结果是？",
    options: ["16", "8", "6", "报错"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "10 % 4 的结果是？",
    options: ["2", "2.5", "0", "1"],
    answer: 0,
    targetLevel: 3,
  },
  {
    q: "(10 + 2) // 3 的结果是？",
    options: ["4", "4.0", "3", "12"],
    answer: 0,
    targetLevel: 3,
  },

  // ---- f-string（对应第4关）----
  {
    q: "name = \"小明\"，下面哪一行能打印出\"你好，小明\"？",
    options: [
      "print(f\"你好，{name}\")",
      "print(\"你好，name\")",
      "print(你好，name)",
      "print{\"你好，\" name}",
    ],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "下面哪个是正确的 f-string 写法？",
    options: ["f\"你好{name}\"", "\"f你好{name}\"", "f\"你好(name)\"", "print f\"你好{name}\""],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "name = \"小红\"，print(f\"{name}你好\") 会输出什么？",
    options: ["小红你好", "{name}你好", "name你好", "会报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "想在一句话里同时显示姓名和年龄两个变量的值，用什么方法最合适？",
    options: ["f-string", "分开print很多次再手动拼起来", "把变量名直接写进普通字符串里", "没办法做到"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "x = 5; print(f\"结果是{x*2}\") 会输出什么？",
    options: ["结果是10", "结果是{x*2}", "结果是x*2", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "f-string 里的花括号 {} 可以放什么？",
    options: ["变量或表达式", "只能放变量", "只能放数字", "什么都不能放"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "下面哪个是正确的 f-string？",
    options: ["f\"值是{x}\"", "\"f值是{x}\"", "f值是{x}", "f\"值是\"{x}"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "不用 f-string，还有其他方法能拼接字符串和变量吗？",
    options: [
      "有，比如用 + 号拼接（需要先转成字符串）",
      "没有，只能用 f-string",
      "只能用 print 多次",
      "只有C语言能做到",
    ],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "name = \"Tom\"; print(f\"{name}\") 和 print(name) 结果一样吗？",
    options: ["一样", "不一样", "会报错", "取决于Python版本"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "f-string 是 Python 哪个版本开始支持的？",
    options: ["3.6+", "2.7", "1.0", "所有版本都支持"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "age = 13，print(f\"我{age}岁了\") 会输出什么？",
    options: ["我13岁了", "我age岁了", "我{age}岁了", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "x = 3; y = 4，print(f\"{x}+{y}={x+y}\") 会输出什么？",
    options: ["3+4=7", "x+y=x+y", "{x}+{y}={x+y}", "报错"],
    answer: 0,
    targetLevel: 4,
  },
  {
    q: "想在 f-string 里显示真正的花括号 {}（而不是当成变量占位符），应该怎么写？",
    options: ["用两个花括号 {{ }}", "用反斜杠 \\{ \\}", "没办法显示花括号", "用中括号 [ ] 代替"],
    answer: 0,
    targetLevel: 4,
  },

  // ---- input（对应第5关）----
  {
    q: "input() 函数的作用是？",
    options: ["让程序暂停，等待用户输入内容", "打印内容", "做数学运算", "创建一个函数"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "name = input(\"你叫什么？\")，用户输入的内容会被存到哪里？",
    options: ["变量 name 里", "直接打印出来，不会保存", "丢失掉", "存到一个列表里"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input() 返回的数据类型是？",
    options: ["字符串（文字）", "整数", "小数", "列表"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "想把 input() 的结果当成数字来做加法，应该怎么做？",
    options: ["用 int() 转换一下", "直接加就行", "input() 自动就是数字", "做不到"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input() 会暂停程序，直到用户做什么？",
    options: ["输入内容并按回车", "关闭浏览器", "点击按钮", "等待5秒"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "想要把 input() 的结果变成整数进行计算，应该怎么做？",
    options: ["int(input())", "input().toInt()", "(int)input()", "input() 自动是整数"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input(\"提示语\") 里的提示语会显示在哪里？",
    options: ["输入前，提示用户要输入什么", "输入后", "不会显示", "只在网页版显示"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "下面哪个说法正确？",
    options: [
      "input() 的返回值永远是字符串类型",
      "input() 的返回值永远是数字",
      "input() 自动判断类型",
      "input() 不能加提示文字",
    ],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "如果用户直接按回车不输入任何内容，input() 会返回什么？",
    options: ["空字符串 \"\"", "None", "报错", "0"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "input() 函数是 Python 的什么？",
    options: ["内置函数", "关键字", "数据类型", "运算符"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "age = input(\"你几岁？\")，用户输入13后按回车，age 的值和类型是？",
    options: ["字符串 \"13\"，不是数字13", "数字13", "None", "报错"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "想让程序先问名字，再问年龄，需要调用几次 input()？",
    options: ["两次，分开写两行", "一次就够，input()能同时问两个问题", "不需要调用input()", "三次"],
    answer: 0,
    targetLevel: 5,
  },
  {
    q: "n = int(input())，如果用户输入的不是数字（比如输入\"abc\"），会发生什么？",
    options: ["报错（无法把\"abc\"转换成整数）", "n会变成0", "n会变成None", "程序会自动忽略这次输入"],
    answer: 0,
    targetLevel: 5,
  },

  // ---- if 判断（对应第6关）----
  {
    q: "score = 55，下面这段代码会打印什么？\nif score >= 60:\n    print(\"及格\")\nelse:\n    print(\"不及格\")",
    options: ["不及格", "及格", "会报错", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if 后面的条件写完，必须要有什么符号？",
    options: ["冒号 :", "分号 ;", "逗号 ,", "感叹号 !"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "下面哪个说法是对的？",
    options: ["else 不能单独出现，必须配合 if 使用", "else 可以单独使用", "if 不需要缩进", "if 只能用一次"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "x = 10\nif x > 5:\n    print(\"A\")\nelse:\n    print(\"B\")\n会输出什么？",
    options: ["A", "B", "AB", "会报错"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if 后面的条件表达式，结果需要是什么？",
    options: ["能判断真假的值", "必须是数字", "必须是字符串", "必须是True或False这两个字面量"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "else 可以脱离 if 单独使用吗？",
    options: ["不可以，必须配合if", "可以，随时能用", "只有在函数里才能单独用", "取决于Python版本"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "一个 if 语句最多能跟几个 elif？",
    options: ["没有限制，可以写很多个", "最多1个", "最多3个", "不能有elif"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if x > 5:\n    print(\"a\")\nprint(\"b\")\n当 x=10 时会打印什么？",
    options: ["a和b都打印", "只打印a", "只打印b", "都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "下面哪个写法会导致语法错误？",
    options: ["if x > 5 print(\"a\")（缺少冒号）", "if x > 5: print(\"a\")", "if (x > 5): print(\"a\")", "if x>5:\n    print(\"a\")"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "not、and、or 是什么？",
    options: ["逻辑运算符，用来组合多个条件", "变量名", "函数名", "数据类型"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "x = 5\nif x > 10:\n    print(\"大\")\nelif x > 3:\n    print(\"中\")\nelse:\n    print(\"小\")\n会打印什么？",
    options: ["中", "大", "小", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "if 5 > 3 and 2 > 4:\n    print(\"yes\")\nelse:\n    print(\"no\")\n会打印什么？",
    options: ["no", "yes", "报错", "什么都不打印"],
    answer: 0,
    targetLevel: 6,
  },
  {
    q: "一个数既要大于0又要小于100才算合法，应该用 and 还是 or 连接这两个条件？",
    options: ["and（两个条件都要满足）", "or（满足一个就行）", "两者效果一样", "都不对，需要用not"],
    answer: 0,
    targetLevel: 6,
  },

  // ---- for 循环（对应第7关）----
  {
    q: "range(1, 4) 依次会产生哪些数字？",
    options: ["1, 2, 3", "1, 2, 3, 4", "0, 1, 2, 3", "1, 4"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(3): print(i) 会打印几行？",
    options: ["3行", "4行", "2行", "0行"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for 循环主要用来做什么？",
    options: ["重复执行一段代码", "判断条件", "存储数据", "定义函数"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "range(5) 里的第一个数字是？",
    options: ["0", "1", "5", "-1"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(3, 8): 会产生哪些数字？",
    options: ["3,4,5,6,7", "3,4,5,6,7,8", "4,5,6,7,8", "3到8所有数（含小数）"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "range(0, 10, 2) 会产生哪些数字？",
    options: ["0,2,4,6,8", "0,1,2...10", "2,4,6,8,10", "0到10所有偶数含10"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for 循环里的变量名（比如 for i in ... 里的 i）能随便起吗？",
    options: ["能，符合变量命名规则就行", "不能，必须叫i", "只能是单个字母", "必须提前声明"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for item in [1,2,3]: 这种写法叫什么？",
    options: ["遍历列表", "创建列表", "删除列表", "排序列表"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for 循环执行的次数由什么决定？",
    options: ["range()或者被遍历对象的长度", "电脑性能", "随机决定", "必须手动写死次数"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "下面哪个循环会打印5次？",
    options: ["for i in range(5)", "for i in range(1,5)", "for i in range(0,5,2)", "for i in range(4)"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "total = 0\nfor i in range(1, 5):\n    total += i\nprint(total)\n会输出什么？",
    options: ["10", "9", "15", "4"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "for i in range(3):\n    print(\"Hi\")\n会打印几次\"Hi\"？",
    options: ["3次", "2次", "4次", "0次"],
    answer: 0,
    targetLevel: 7,
  },
  {
    q: "想遍历列表 fruits 里的每一个元素并打印出来，应该怎么写？",
    options: ["for f in fruits:\n    print(f)", "for fruits in f:\n    print(f)", "while fruits: print(f)", "print(fruits[all])"],
    answer: 0,
    targetLevel: 7,
  },

  // ---- while 循环（对应第8关）----
  {
    q: "while 循环会在什么情况下停止？",
    options: ["条件变成 False", "永远不会停止", "执行一次后自动停止", "遇到 print 就停止"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "下面哪段代码会变成\"死循环\"（永远停不下来）？",
    options: [
      "count = 1\nwhile count < 5:\n    print(count)",
      "count = 1\nwhile count < 5:\n    print(count)\n    count = count + 1",
      "for i in range(5):\n    print(i)",
      "print(\"hello\")",
    ],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while 和 for 循环最主要的区别是？",
    options: [
      "while更适合\"不确定要循环几次，只看条件满不满足\"的情况",
      "while只能循环1次",
      "while不能配合if使用",
      "两者完全没有区别",
    ],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "count = 0\nwhile count < 3:\n    count = count + 1\n执行结束后 count 最终是多少？",
    options: ["3", "2", "0", "死循环，不会结束"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while True: 会发生什么？",
    options: ["无限循环，除非里面有break等方式跳出", "立刻结束", "报错", "只执行一次"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while循环和for循环，哪个更适合\"不知道要循环几次，只看条件\"的场景？",
    options: ["while", "for", "两者一样", "都不适合"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "break 关键字在循环里的作用是？",
    options: ["立刻跳出当前循环", "跳过这一次循环", "结束整个程序", "重新开始循环"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "continue 关键字在循环里的作用是？",
    options: ["跳过这一次循环剩下的代码，继续下一次循环", "立刻跳出循环", "结束程序", "什么都不做"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "while循环最容易犯的错误是什么？",
    options: ["忘记让条件变化，导致死循环", "变量名起错", "忘记print", "用了中文标点"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "下面哪段代码会立刻结束循环，不打印任何东西？",
    options: ["while False: print(\"a\")", "while True: print(\"a\")", "while 1: print(\"a\")", "for i in range(1): print(\"a\")"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "n = 5\nwhile n > 0:\n    n -= 1\nprint(n)\n最终会打印什么？",
    options: ["0", "5", "1", "死循环"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "i = 0\nwhile i < 3:\n    print(i)\n    i += 1\n会依次打印哪些数字？",
    options: ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "只打印0"],
    answer: 0,
    targetLevel: 8,
  },
  {
    q: "写 while 循环时，循环体里通常需要做什么，才能避免死循环？",
    options: ["让循环条件相关的变量发生变化", "多写几个print", "把条件写成True", "什么都不用做"],
    answer: 0,
    targetLevel: 8,
  },

  // ---- 列表（对应第9关）----
  {
    q: "fruits = [\"苹果\", \"香蕉\", \"橙子\"]，fruits[1] 是？",
    options: ["香蕉", "苹果", "橙子", "会报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "列表用什么符号来定义？",
    options: ["方括号 []", "花括号 {}", "圆括号 ()", "尖括号 <>"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [10, 20, 30]，nums[0] 是？",
    options: ["10", "20", "30", "会报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "想把一个新元素加到列表末尾，用哪个方法？",
    options: [".append()", ".add()", ".insert(0)", ".push()"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "len([1,2,3,4]) 的结果是？",
    options: ["4", "3", "[1,2,3,4]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1,2,3]; nums.append(4) 之后 nums 是？",
    options: ["[1,2,3,4]", "[4,1,2,3]", "[1,2,3]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "列表可以装不同类型的数据吗（比如同时装数字和文字）？",
    options: ["可以", "不可以，必须都是同一类型", "只有字符串列表可以", "取决于Python版本"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums[1:3] 这种写法叫什么？",
    options: ["切片，取出下标1到2（不含3）的部分", "取第1到第3个", "报错", "删除操作"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "空列表怎么创建？",
    options: ["[]", "{}", "()", "null"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "列表是有序的吗（元素的顺序会保留吗）？",
    options: ["是的，顺序和添加时一致", "不是，会自动排序", "不是，顺序随机", "取决于元素类型"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1, 2, 3]，nums[-1] 的结果是？",
    options: ["3", "1", "报错", "None"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [1, 2, 3]\nnums.remove(2)\nprint(nums)\n会输出什么？",
    options: ["[1, 3]", "[1, 2, 3]", "[2]", "报错"],
    answer: 0,
    targetLevel: 9,
  },
  {
    q: "nums = [5, 3, 8, 1]\nnums.sort()\nprint(nums)\n会输出什么？",
    options: ["[1, 3, 5, 8]", "[5, 3, 8, 1]", "[8, 5, 3, 1]", "报错"],
    answer: 0,
    targetLevel: 9,
  },

  // ---- 字典（对应第10关）----
  {
    q: "字典用什么符号来定义？",
    options: ["花括号 {}", "方括号 []", "圆括号 ()", "双引号 \"\""],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "person = {\"name\": \"小明\", \"age\": 13}，怎么取出年龄？",
    options: ["person[\"age\"]", "person[age]", "person.age", "person(age)"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "字典和列表最大的不同是？",
    options: [
      "字典用\"键\"取值，列表用\"位置(下标)\"取值",
      "字典不能存文字",
      "列表不能存数字",
      "两者没有区别",
    ],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "{\"a\": 1, \"b\": 2} 这个字典里有几对键值？",
    options: ["2", "1", "3", "0"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "字典的键（key）可以重复吗？",
    options: ["不可以，重复会覆盖之前的值", "可以，都会保留", "可以，但会报警告", "取决于值的类型"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "怎么判断一个键在不在字典里？",
    options: ["\"键\" in 字典", "字典.has(\"键\")", "字典.contains(\"键\")", "字典[\"键\"] == True"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "person = {\"name\": \"小明\"}; person[\"age\"] = 13 之后会发生什么？",
    options: ["给字典新增一个age键值对", "报错，因为age键不存在", "什么都不会发生", "覆盖name的值"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "字典的键一般用什么类型？",
    options: ["字符串或数字这类不可变类型", "只能是字符串", "只能是数字", "可以是列表"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "空字典怎么创建？",
    options: ["{}", "[]", "()", "dict[]"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "person.get(\"age\", 0) 这行代码的意思是？",
    options: ["取age的值，如果不存在返回默认值0", "把age设成0", "删除age这个键", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d = {\"a\": 1, \"b\": 2}\ndel d[\"a\"]\nprint(d)\n会输出什么？",
    options: ["{'b': 2}", "{'a': 1}", "{}", "报错"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "d = {}\nd[\"x\"] = 10\nprint(d[\"x\"])\n会输出什么？",
    options: ["10", "\"x\"", "None", "报错，d是空字典不能赋值"],
    answer: 0,
    targetLevel: 10,
  },
  {
    q: "想遍历字典 d 的所有键，应该怎么写？",
    options: ["for key in d:", "for key in d.values():", "for d in key:", "while d:"],
    answer: 0,
    targetLevel: 10,
  },

  // ---- 函数（对应第11关）----
  {
    q: "def 关键字在 Python 里是用来做什么的？",
    options: ["创建一个函数", "创建一个变量", "写一个判断条件", "写一个循环"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "函数最大的好处是？",
    options: ["避免重复写同样的代码", "让代码运行变快", "让代码变得更长", "没有好处"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "下面哪一个是正确定义函数的写法？",
    options: ["def greet(name):", "function greet(name):", "def greet(name)", "greet(name):"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "调用一个已经定义好的函数 greet，应该怎么写？",
    options: ["greet(\"小明\")", "def greet(\"小明\")", "call greet(\"小明\")", "greet[\"小明\"]"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "函数如果没有 return 语句，调用它会返回什么？",
    options: ["None", "0", "空字符串", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def greet(name=\"小明\"): 这种写法叫什么？",
    options: ["默认参数", "必填参数", "返回值", "局部变量"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "函数内部创建的变量，函数外面能访问吗？",
    options: ["不能，这是局部变量", "能，所有变量都是全局的", "取决于变量名", "只有数字类型不能"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "调用函数和定义函数，哪个要写在前面？",
    options: ["必须先定义，再调用", "必须先调用，再定义", "顺序不影响", "只要在同一个文件就行"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "return 和 print 在函数里的区别是？",
    options: [
      "return把值返回给调用者可以继续用，print只是显示在屏幕上",
      "没有区别",
      "return更快",
      "print不能在函数里用",
    ],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def add(a, b): return a + b，调用 add(3, 5) 的结果是？",
    options: ["8", "35", "报错", "None"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def square(x):\n    return x * x\nprint(square(4))\n会输出什么？",
    options: ["16", "8", "4", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "def greet(name):\n    print(f\"你好，{name}\")\ngreet(\"小明\")\n会输出什么？",
    options: ["你好，小明", "你好，name", "greet(小明)", "报错"],
    answer: 0,
    targetLevel: 11,
  },
  {
    q: "一个函数可以同时接收多个参数吗？",
    options: ["可以，用逗号隔开多个参数", "不可以，只能有一个参数", "最多只能有两个参数", "取决于返回值类型"],
    answer: 0,
    targetLevel: 11,
  },
];
